---

- name: "Copy K3s service file"
  ansible.builtin.template:
      src: "k3s-agent.service.j2"
      dest: "{{ systemd_dir }}/k3s-agent.service"
      owner: root
      group: root
      mode: '0755'

- name: "Copy K3s Agent service env file"
  ansible.builtin.template:
      src: "k3s-agent.service.env.j2"
      dest: "{{ systemd_dir }}/k3s-agent.service.env"
      owner: root
      group: root
      mode: '0644'

- name: "Enable and check K3s service"
  ansible.builtin.systemd:
      name: k3s-agent
      daemon_reload: true
      state: restarted
      enabled: true

...
