---

- name: "Download k3s binary x64"
  ansible.builtin.get_url:
      url: "{{ k3s_url }}"
      checksum: "{{ k3s_checksum }}"
      dest: /usr/local/bin/k3s
      owner: root
      group: root
      mode: "0755"
  when: ansible_facts.architecture == "x86_64"
