---

- name: "Create directory .kube"
  ansible.builtin.file:
    path: ~{{ ansible_user }}/.kube
    state: directory
    owner: "{{ ansible_user }}"
    mode: "u=rwx,g=rx,o="

- name: "Copy config file to user home directory"
  ansible.builtin.copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ~{{ ansible_user }}/.kube/config
    remote_src: true
    owner: "{{ ansible_user }}"
    mode: "u=rw,g=,o="

- name: "Replace https://localhost:6443 by https://master-ip:6443"
  ansible.builtin.command: >-
    k3s kubectl config set-cluster default
      --server=https://{{ k3s_master_ip }}:6443
      --kubeconfig ~{{ ansible_user }}/.kube/config
  changed_when: true

- name: "Create kubectl symlink"
  ansible.builtin.file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/kubectl
    state: link

- name: "Create crictl symlink"
  ansible.builtin.file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/crictl
    state: link

- name: "Create ctr symlink"
  ansible.builtin.file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/ctr
    state: link
