---

- name: "Master Copy K3s service file"
  register: k3s_service
  ansible.builtin.template:
      src: "k3s.service.j2"
      dest: "{{ systemd_dir }}/k3s.service"
      owner: root
      group: root
      mode: "0644"

- name: "Copy K3s Master service env file"
  ansible.builtin.template:
      src: "k3s.service.env.j2"
      dest: "{{ systemd_dir }}/k3s.service.env"
      owner: root
      group: root
      mode: "0644"

- name: "Enable and check K3s service"
  ansible.builtin.systemd:
      name: k3s
      daemon_reload: true
      state: restarted
      enabled: true

...
