---

- name: "Create directory /etc/rancher/k3s/ if it does not exist"
  ansible.builtin.file:
    path: /etc/rancher/k3s/
    state: directory
    mode: "0755"
    recurse: true

- name: "Master Copy K3s service file"
  ansible.builtin.template:
    src: registries.yaml.j2
    dest: /etc/rancher/k3s/registries.yaml
    owner: root
    group: root
    mode: "0644"
